name: matrix-lib-proj
version: 0.1.0.0
github: "KubEF/matrix-lib-proj"
license: BSD3
author: "Kubishkin Efim"
maintainer: "efimkub@mail.ru"
copyright: "2023 Kubishkin Efim"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/KubEF/matrix-lib#readme>

dependencies:
  - base >= 4.7 && < 5
  - template-haskell
  - deepseq

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

language: GHC2021

executables:
  matrix-lib-proj-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - matrix-lib-proj

tests:
  matrix-lib-proj-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - matrix-lib-proj
      - HUnit

benchmarks:
  testing-bench:
    source-dirs: bench
    main: Main.hs
    dependencies:
      - criterion
      - random
      - matrix-lib-proj
